# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        env:
          HELLO_NAME: "world"
        run: |
          echo Hello $HELLO_NAME !
          echo $GITHUB_ENV
          echo $NODE_OPTIONS
          echo "HELLO_NAME=namenlos" >> $GITHUB_ENV
          echo "NODE_OPTIONS=eto_prikol" >> $GITHUB_ENV
          echo "VALUE_MY=somehing with whitespaces" >> $GITHUB_ENV
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script444
        run: |
          echo $HOME
          cd
          ls
          HOME=/home/runner/work/_temp/_runner_file_commands/
          cd
          echo
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script44
        run: |
          echo $HOME
          echo Hello from $GITHUB_ENV
          GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/ahahahahah
          touch GITHUB_ENV
          echo "KEKEKE=banana" >> $GITHUB_ENV
          echo Hallo $HELLO_NAME
          echo $NODE_OPTIONS
          echo $VALUE_MY

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo $HOME
          echo Hello from $GITHUB_ENV
          echo Hallo $HELLO_NAME
          echo Banana? $KEKEKE !!
          ls /home/runner/work/_temp/_runner_file_commands/
          cat /home/runner/work/_temp/_runner_file_commands/ahahahahah
          echo $NODE_OPTIONS
          echo $VALUE_MY
          echo "HOME=/home/runner/work/_temp/_runner_file_commands/" >> $GITHUB_ENV

      - name: Run a multi-line script2
        run: |
          echo $HOME
          cd
          ls
          echo Hello from $GITHUB_ENV
          echo Hallo $HELLO_NAME
          echo "HELLO_NAME=privet" >> $GITHUB_ENV
          ls /home/runner/work/_temp/_runner_file_commands/
          rm $GITHUB_ENV
          echo $NODE_OPTIONS
          echo $VALUE_MY

      - name: Run a multi-line script3
        run: |
          echo Hello from $GITHUB_ENV
          echo Hallo $HELLO_NAME
          echo $NODE_OPTIONS
          echo $VALUE_MY
